### ISSUE TITLE
Bug reporte maligno

### ISSUE THREAD

**Issue by Cachorro112** [gabrieldodrip990/carlinhos-station#1]
olá, hoje estou aqui para contar a historia de como eu vi o carlinhos no server Carlinhos Station 13.
tudo começou depois que eu sai do banheiro depois de bater uma fappada sinistra, eu me masturbei para o boneco do player Renniar chamada: "Janita", após isso, sentei no computador e entrei no discord, como sempre eu xinguei o Manlekvf de pedofilo e abri o byond, assim que eu abri o byond, um som estranho tocou, o click do byond, mas parecia um som de gosma estranha, mas eu ignorei, achei que era algum update do byond. dai eu peguei o IP do server de gabriel e entrei no servidor como eu sempre fiz, assim que eu colei o IP, mandaram uma mensagem para mim no discord, era um usuario chamado Hugo da Silva, a foto de perfil dele era um humem negro com a piroca cortada ao meio, eu pensei em bloquear, mas então eu abri para ver oque ele mandou, era um video do carlinhos, uma edit na verdade, do carlinhos falando que chupava homens e logo depois, ele dizia que o space station 13 estava morto e que eu devia parar de jogar imediatamente, caso contrario toda minha familia e dos outros players seria morta, eu ignorei achando que era só um meme, mas eu estava completamente enganado.

Certo, dai eu voltei a jogar, entrei como engenheiro e já fui fazer sexo no bar, encontrei a gabriela a sa e estuprei ela violentamente, então fui ligar o reator de super materia, ao chegar na engine, noto que toda a eng estava ejaculada e cheia de fezes, eu estranhei, já que não tem como ter fezes no codigo, eu falei no radio se haviam cagado na eng e todos negaram. então eu fui e ativer o reator, mas eu notei algo: tinha um humano dentro do reator, ele se chamava "Carlos", ele vestia uma blusa do corintians e estava olhando para mim, eu falei: "Quem é você?" ai ele respondeu: "Seu maior medo." nesse momento eu já havia me cagado todo, eu fiz ahelp para o host gabriel o louco, mas ele não me respondeu, então o Carlos falou: "Gabriel está morto." eu pensei que era brincadeira, mas o boneco do gabriel estava AFK há 20 minutos já, eu começei a me tremer e ativei a SM para explor, assim que ela explodiu, o carlinhos sumiu, então eu fechei o jogo... mas eu senti uma respiração no meu pescoço e uma voz falou no meu ouvido: "2050 players estão mortos."...

**Comment by gabrieldodrip990** [comment]
https://github.com/user-attachments/assets/58771e0a-cf7c-4378-8554-434f4c34fd18

muito lamentavel essa historia, muito triste(essa mensagem foi enviado por carlinhos por gabriel estar morto MUAHAHAHAHAHAHAHAHAHAHHA)

**Comment by Cachorro112** [comment]
https://github.com/user-attachments/assets/41b04708-bfa7-4a3a-826a-45fabe7f9e18

**Comment by Cachorro112** [comment]
eu indo matar e estuprar o gabriel el louco

**Comment by gabrieldodrip990** [comment]
ATE NO GITHUB???
